require 'dotenv'
fastlane_version '2.44.1'

default_platform :ios

lane :prod do
  # retrieves ENV
  Dotenv.load('.env', '.env.prod')

  set_javascript_environment

  # code sign the app
  match(shallow_clone: true, force: true)

  # prepare the ios App settings
  xcodeproj_path = "./#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PROJECT_NAME']}.xcodeproj"

  disable_automatic_code_signing(path: xcodeproj_path)
  update_info_plist(
    xcodeproj: xcodeproj_path,
    display_name: ENV['IOS_APP_NAME'],
    app_identifier: ENV['IOS_APP_ID'],
    plist_path: "#{ENV['IOS_APP_NAME']}/Info.plist",
  )

  # build your iOS app
  gym(
    silent: true,
    scheme: ENV['IOS_APP_NAME'],
    export_method: 'ad-hoc',
    project: xcodeproj_path,
    xcargs: "DEVELOPMENT_TEAM='#{ENV['IOS_TEAM_ID']}'"
  )

  # upload to HockeyApp
  hockey(notify: '0')
end

lane :set_javascript_environment do
  backup_file(path: 'src/environment/index.js')
  sh "cp ../src/environment/env.#{ENV['ENV']}.js ../src/environment/index.js"
end

# roll back JS environment file
after_all do |lane, options|
  if File.exist?('../src/environment/index.js.back')
    restore_file(path: 'src/environment/index.js')
  end
end
